name: Auto-Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Action Docs
        uses: pndurette/gh-actions-auto-docs@v1
        with:
          action_yaml_file: ./action.yaml
          target_file: ./README.md
          git_push: true
